server:
  port: 8001
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  data:
    mongodb:
      host: localhost
      port: 27001
      database: band