server:
  port: 8000
spring:
  cloud: 
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/piterrivero/MSProject
          search-paths: config-data
  application:
    name: config-service
